version: "3.3"
services:
    nginx:
        image: nginx:alpine
        ports: 
            - 80:80
        volumes: 
            - .\conf\nginx.conf:/etc/nginx/nginx.conf:ro
            - .\conf\conf.d:/etc/nginx/conf.d
            - .\html:/usr/share/nginx/html
    php:
        image: devilbox/php-fpm:7.3-work-0.106
        volumes:
            - .\html:/var/www/html/
    mysql:
        image: mysql:5.7.29
        volumes:
            - .\mysql:/var/lib/mysql
            - .\conf\mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - .\conf\mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - .\conf\docker.cnf:/etc/mysql/conf.d/docker.cnf
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"